name: Test electron-chrome-extensions

on:
  push:
    paths:
      - 'packages/**'
  pull_request:
    paths:
      - 'packages/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun build

      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        uses: GabrielBB/xvfb-action@v1
        with:
          run: bun test

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: bun test
